### ISSUE TITLE
Contrary to expected result

### ISSUE THREAD

**Issue by RachelRen05** [intel/ros_intel_movidius_ncs#89] opened 2018-04-24 06:23 UTC
ncappzoo is the latest code.
cd /opt/movidius/ncappzoo/tensorflow/mobilenets
make
will not generate **graph** in current directory,will generate **graph** in the **model** directory.

**Comment by chaoli2** [comment] 2018-04-25 05:56
fixed with PR #91

**Comment by xhuan28** [comment] 2018-04-25 06:41
This issue is caused by the update of the ncappzoo. They put graph file in model folder in the latest commit. You can change the default path of graph in configuration file or  use the PR #91 alternatively.

**Comment by RachelRen05** [comment] 2018-04-28 08:37
This issue has been verified to be correct.

**Closed as completed** 2018-05-06 03:40 UTC
Labels: bug
